spring:
  application:
    name: how-much-is-my-hot-wheels
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/hotwheels_db?authSource=admin
      auto-index-creation: true

server:
  port: 8080

etsy:
  api:
    key: ${ETSY_API_KEY}